### ISSUE TITLE
cf-service-info plugin

### ISSUE THREAD

**Issue by princeneil** [SAP/cloud-foundry-tools#100]
Hi

Where can I get/install the cli plugin cf-service-info. I can see from issue 6, that a reference was previously given to an internal SAP repository [http://nexus.wdf.sap.corp:8081/nexus/content/groups/build.releases/com/sap/golang/com/sap/devx/wing/cfserviceinfo/] which obviously I cannot access. It is not available in the CF-Community respository of CF.

I have installed this extension into VS Code, however, it does not work without this component. Is Cf-service-info available to the public?

Regards
Neil

**Comment by alex-gilin** [comment]
Hello @princeneil .
 You're right - the 'ServiceInfo' plugin is currently not available in the CF public repository for legal reasons. Therefore, the ability to bind a service is not available through the extension. But the rest of the functionality is available through the command palette:> CF: like logging in, creating a new (user-managed and user-provided) service, choosing an organization and space ...
We are sorry for the inconvenience.

BR, AG

**Comment by piejanssens** [comment]
Can we keep this issue open to follow up on this at a later stage when the plugin would become publicly available?
