### ISSUE TITLE
run the launch config 'Run Extension' Please provide more details

### ISSUE THREAD

**Issue by DenisGalandSAP** [SAP/cloud-foundry-tools#192]
Hello,

I am trying to install the tool, but about the step 
_Run the launch config 'Run Extension'_
I don't know what to do, I'm searching in the internet but I can't find what exactly what we have to do at that point.
Could you elaborate a little bit more?

Thanks & regards

Denis

**Comment by alex-gilin** [comment]
@DenisGalandSAP , 
I've updated the README.md
Sorry for inaccuracy. 
In case you do not need the debug, just download the packed vsix (from releases) and install it in your vscode locally.
BR, AG

**Comment by DenisGalandSAP** [comment]
Ah ok I didn't see a vsix is available, it is not mentioned in the readme.md.
It is installed now and I can use it, thank you for the reply :)

Denis
