### ISSUE TITLE
'targets' is not a registered command. See 'cf help -a' Did you mean? target

### ISSUE THREAD

**Issue by rayatus** [SAP/cloud-foundry-tools#236]
I've just installed VSIX v7.0.3 in my local VSCode 1.70.1.
then CF icon extension appears
but when I click on it i get following error "'targets' is not a registered command. See 'cf help -a' Did you mean? target"

**Comment by koudayao27** [comment]
you need to install the cf-targets plugin
https://github.com/guidowb/cf-targets-plugin

``` 
$ cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org/
$ cf install-plugin Targets -r CF-Community
```

**Comment by yaosheng79** [comment]
you need to install the cf-targets plugin
https://github.com/guidowb/cf-targets-plugin

``` 
$ cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org/
$ cf install-plugin Targets -r CF-Community
```
