### ISSUE TITLE
'targets' is not a registered command. 

### ISSUE THREAD

**Issue by VolkerSaggau** [SAP/cloud-foundry-tools#284]
'targets' is not a registered command. See 'cf help -a' Did you mean? target

Hi, 

I do get this error message using the VSIX on a Mac. HANA DB Exlplorer seems to work but the VSIX has issues.
What do I do wrong ?

BR
Volker Saggau

**Comment by rimasirich** [comment]
Hi @VolkerSaggau ,

'targets' plugin is cloud-foundry-tools prerequisite as documented [here](https://github.com/SAP/cloud-foundry-tools?tab=readme-ov-file#dependencies)
to install it run following command in the terminal: 
```sh
cf install-plugin -r CF-Community "Targets"
```
Regards,
Rima
