### ISSUE TITLE
Url doesnt work

### ISSUE THREAD

**Issue by d-sooter** [SAP/cloud-foundry-tools#6]
The link provides seems to be an internal link 

cf-cli extension called cf-service-info (from here)[http://nexus.wdf.sap.corp:8081/nexus/content/groups/build.releases/com/sap/golang/com/sap/devx/wing/cfserviceinfo/]

The run config mentioned is not included in the project 

"run the launch config 'Run Extension'"

Thanks in advance

**Comment by alex-gilin** [comment]
Separation from inner packaging [completed](https://github.com/SAP/cloud-foundry-tools/pull/23)
